#!/usr/bin/env python3
"""
update-anthropic-models.py

Zed (since PR #56397) populates the Anthropic model dropdown by fetching
GET {api_url}/v1/models and deserializing each entry into a struct that
*requires* `id`, `display_name`, `max_input_tokens` and `max_tokens`.

CLIProxyAPI's /v1/models returns an OpenAI-style list ({id, object, created,
owned_by}) with none of that metadata, so Zed's parse fails and the dropdown
ends up empty (zed issue #56880). The proxy's *inference* path (/v1/messages)
is fully Anthropic-native and works fine — only model *discovery* is broken.

This script bridges the gap: it pulls the model ids from the proxy and writes
a fully-formed `language_models.anthropic.available_models` block into your
Zed settings.json, supplying `max_tokens` / `max_output_tokens` from the table
below. Zed merges a manually-declared available_models list in regardless of
the failing fetch, so the models show up; all real traffic then flows over the
working native /v1/messages path.

Where the token numbers come from
---------------------------------
The proxy can't report them, and the real Anthropic /v1/models (which does
carry them) needs a first-party API key you don't have on a Max subscription.
So the values come from Anthropic's *published* per-model limits, encoded in
MODEL_DEFAULTS below. Notes:
  * max_tokens here is the CONTEXT WINDOW (Zed's name for max input tokens).
    NOTE: Zed uses this only as the token-budget gauge — it is NOT sent to the
    API, so setting it high cannot itself cause a rejection. We therefore use
    each model's true published window: 1M for Opus 4.6/4.7/4.8 and Sonnet
    4/4.5/4.6 (the Sonnet 4.x ones via the 1M-context beta), 200K for the rest.
    Drop a model back to 200_000 if you find the upstream actually rejects
    large-context requests for it.
  * max_output_tokens DOES get sent as the per-response max_tokens. Set it at
    or under the model's real output ceiling to avoid upstream 400s.

It is idempotent: the generated block is fenced with marker comments, so
re-running replaces that block in place and leaves the rest of your (JSONC,
comments-and-trailing-commas) settings file untouched. A timestamped backup is
written before any change.

Usage:
    ./update-anthropic-models.py                     # auto-detect everything
    ./update-anthropic-models.py --base-url http://localhost:8317
    ./update-anthropic-models.py --api-key sk-...     # if your proxy needs auth
    ./update-anthropic-models.py --dry-run            # print, don't write

Env vars (used if flags omitted):
    CLIPROXY_BASE_URL, CLIPROXY_API_KEY, ZED_SETTINGS
"""

import argparse
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request

DEFAULT_SETTINGS = os.path.expanduser("~/.config/zed/settings.json")
DEFAULT_BASE_URL = "http://localhost:8317"

# ---------------------------------------------------------------------------
# Per-model token limits, sourced from Anthropic's published specs.
# Matched as a substring of the model id, FIRST match wins, so order
# specific -> general. Edit freely; these only affect Zed's token budgeting
# and the cap it places on a single response.
#   (id-substring, max_tokens / context-window, max_output_tokens)
# ---------------------------------------------------------------------------
MODEL_DEFAULTS = [
    # (id-substring, context window, max output) — FIRST match wins, so order specific -> general.
    ("opus-4-8",   1_000_000, 64_000),  # Opus 4.8 — 1M context (real output ceiling 128K; 64K is a sane cap)
    ("opus-4-7",   1_000_000, 64_000),  # Opus 4.7 — 1M context
    ("opus-4-6",   1_000_000, 64_000),  # Opus 4.6 — 1M context
    ("opus-4-5",     200_000, 64_000),  # Opus 4.5 — 200K context
    ("opus-4-1",     200_000, 32_000),  # Opus 4.1 — 200K context
    ("opus-4",       200_000, 32_000),  # Opus 4.0 — 200K context
    ("sonnet-4-6", 1_000_000, 64_000),  # Sonnet 4.6 — 1M context
    ("sonnet-4-5", 1_000_000, 64_000),  # Sonnet 4.5 — 1M context (via 1M beta)
    ("sonnet-4",   1_000_000, 64_000),  # Sonnet 4.0 — 1M context (via 1M beta)
    ("3-7-sonnet",   200_000, 64_000),  # Sonnet 3.7 — 200K context
    ("haiku-4",      200_000, 64_000),  # Haiku 4.5 — 200K context
    ("3-5-haiku",    200_000,  8_192),  # Haiku 3.5 — 200K context
]
DEFAULT_CONTEXT = 200_000
DEFAULT_OUTPUT  =   8_192

MARK_BEGIN = "// >>> anthropic available_models — auto-generated by update-anthropic-models.py (edit MODEL_DEFAULTS, not this block) >>>"
MARK_END   = "// <<< anthropic available_models <<<"


def log(msg):
    print(msg, file=sys.stderr)


def fetch_models(base_url, api_key):
    url = base_url.rstrip("/") + "/v1/models?limit=1000"
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    if api_key:
        req.add_header("Authorization", f"Bearer {api_key}")
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            payload = json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as e:
        log(f"ERROR: could not reach {url}: {e}")
        log("Is CLIProxyAPI running? Try: curl -s " + url)
        sys.exit(1)
    except json.JSONDecodeError as e:
        log(f"ERROR: /v1/models did not return JSON: {e}")
        sys.exit(1)
    data = payload.get("data")
    if not isinstance(data, list):
        log("ERROR: response had no `data` array; got: " + json.dumps(payload)[:300])
        sys.exit(1)
    return data


def is_anthropic(entry):
    owned = (entry.get("owned_by") or "").lower()
    mid = (entry.get("id") or "")
    return owned == "anthropic" or mid.startswith("claude")


def pretty_name(model_id):
    out, ver = [], []

    def flush():
        if ver:
            out.append(".".join(ver))
            ver.clear()

    for p in model_id.split("-"):
        if p.isdigit() and len(p) >= 7:      # snapshot date like 20250514
            continue
        if p.isdigit():                       # version fragment
            ver.append(p)
            continue
        flush()
        low = p.lower()
        if low == "latest":
            continue
        if low == "claude":
            out.append("Claude")
        elif low in ("opus", "sonnet", "haiku"):
            out.append(p.capitalize())
        elif low == "1m":
            out.append("1M")
        elif low == "context":
            out.append("Context")
        else:
            out.append(p.capitalize())
    flush()
    return " ".join(out) if out else model_id


def limits_for(model_id):
    for needle, ctx, outp in MODEL_DEFAULTS:
        if needle in model_id:
            return ctx, outp
    return DEFAULT_CONTEXT, DEFAULT_OUTPUT


def build_entries(data):
    seen, entries = set(), []
    for e in data:
        if not is_anthropic(e):
            continue
        mid = e.get("id")
        if not mid or mid in seen:
            continue
        seen.add(mid)
        ctx, outp = limits_for(mid)
        entries.append({
            "_created": e.get("created", 0),
            "name": mid,
            "display_name": pretty_name(mid),
            "max_tokens": ctx,
            "max_output_tokens": outp,
        })
    # newest first (falls back to id order when created is missing/equal)
    entries.sort(key=lambda x: (-(x["_created"] or 0), x["name"]))
    for x in entries:
        x.pop("_created", None)
    return entries


def render_block(entries, indent=6):
    pad = " " * indent
    field = " " * (indent + 4)
    item = " " * (indent + 2)
    lines = [MARK_BEGIN, f'{pad}"available_models": [']
    for e in entries:
        lines.append(f"{item}{{")
        lines.append(f'{field}"name": {json.dumps(e["name"])},')
        lines.append(f'{field}"display_name": {json.dumps(e["display_name"])},')
        lines.append(f'{field}"max_tokens": {e["max_tokens"]},')
        lines.append(f'{field}"max_output_tokens": {e["max_output_tokens"]}')
        lines.append(f"{item}}},")
    lines.append(f"{pad}],")
    lines.append(f"{pad}{MARK_END}")
    return "\n".join(lines)


def splice(text, block):
    """Insert or replace the marker-fenced block inside the anthropic provider object."""
    if MARK_BEGIN in text:
        pattern = re.compile(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END), re.DOTALL)
        return pattern.sub(lambda _m: block, text, count=1), "replaced existing block"

    m = re.search(r'"anthropic"\s*:\s*\{', text)
    if not m:
        log('ERROR: no `"anthropic": { ... }` object found under language_models in settings.json.')
        log("Add one first, e.g.:")
        log('    "language_models": { "anthropic": { "api_url": "http://localhost:8317" } }')
        sys.exit(1)

    if re.search(r'"available_models"', text):
        log("ERROR: settings.json already contains an `available_models` key but no")
        log("       auto-generated markers. Remove that key (or add the marker comments")
        log("       around it) so this script can manage it safely. Aborting to avoid")
        log("       creating a duplicate key.")
        sys.exit(1)

    insert_at = m.end()
    new_text = text[:insert_at] + "\n" + " " * 6 + block + text[insert_at:]
    return new_text, "inserted new block"


def main():
    ap = argparse.ArgumentParser(description="Populate Zed's Anthropic available_models from a CLIProxyAPI /v1/models endpoint.")
    ap.add_argument("--settings", default=os.environ.get("ZED_SETTINGS", DEFAULT_SETTINGS))
    ap.add_argument("--base-url", default=os.environ.get("CLIPROXY_BASE_URL"))
    ap.add_argument("--api-key", default=os.environ.get("CLIPROXY_API_KEY"))
    ap.add_argument("--dry-run", action="store_true", help="print the result, write nothing")
    args = ap.parse_args()

    settings_path = os.path.expanduser(args.settings)
    if not os.path.exists(settings_path):
        log(f"ERROR: settings file not found: {settings_path}")
        sys.exit(1)
    with open(settings_path, "r", encoding="utf-8") as f:
        text = f.read()

    # base url precedence: flag/env -> api_url from settings.json -> default
    base_url = args.base_url
    if not base_url:
        m = re.search(r'"anthropic"\s*:\s*\{[^{}]*?"api_url"\s*:\s*"([^"]+)"', text, re.DOTALL)
        base_url = m.group(1) if m else DEFAULT_BASE_URL
    log(f"• proxy:    {base_url}")

    data = fetch_models(base_url, args.api_key)
    entries = build_entries(data)
    if not entries:
        log("ERROR: no Anthropic/claude models found in /v1/models response.")
        sys.exit(1)
    log(f"• models:   {len(entries)} found")
    for e in entries:
        log(f"    - {e['name']:<32} -> {e['display_name']}  (ctx {e['max_tokens']}, out {e['max_output_tokens']})")

    block = render_block(entries)
    new_text, action = splice(text, block)

    if args.dry_run:
        log(f"• dry-run:  would have {action}; result below\n")
        print(new_text)
        return

    if new_text == text:
        log("• no change: settings already up to date.")
        return

    backup = f"{settings_path}.{time.strftime('%Y%m%d-%H%M%S')}.bak"
    with open(backup, "w", encoding="utf-8") as f:
        f.write(text)
    with open(settings_path, "w", encoding="utf-8") as f:
        f.write(new_text)
    log(f"• backup:   {backup}")
    log(f"• updated:  {settings_path} ({action})")
    log("Done. Reopen the Zed Agent panel / model picker to see the models.")


if __name__ == "__main__":
    main()
